Public Class UKOLegalPlus
    ''master tables
    Public Function getTables() As DataTable
        Dim dt As New DataTable
        dt.Columns.Add("Schema")
        dt.Columns.Add("TableName")
        dt.Columns.Add("Filter")

        dt.Rows.Add("Crawling", "DimECourt_New", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimAcCategory", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimAcClosure", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimAcSplCategory", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimActivity", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimAddressCategory", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimAdjournReasonMobAAP", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimAlertMessage", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimArea", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimAssetClass", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimAssetsNature", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimAuthority", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DIMBANK", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimBankingArrangement", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimBranch", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimBranchDetail", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimCase", "")
        dt.Rows.Add("dbo", "DimCaseStaging", "")
        dt.Rows.Add("dbo", "DimCaste", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimCity", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimConsortiumType", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimConstitution", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimCountry", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimCurrency", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimDefaultReason", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimDesignation", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimDocument", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimFarmerCat", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimGeography", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimGL", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DIMGLPRODUCT", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimInsuranceComp", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimInttType", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimLegalAdvCategory", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimLegalSRFCauseOfActionDtls", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimMaritalStatus", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimMaxLoginAllow", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimNBFC", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimNCLT_Branch", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimNewsPaper", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimOccupation", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimParameter", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimPassportLocation", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimPincode", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DIMPRODUCT", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimProfessionalDetailForNCLT", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DImProfessionData", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "Dimproftemp", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimQualification", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimReasonForWillfulDefault", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimRegion", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimRelationEntities", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimReligion", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimRepaymentMode", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimReportFrequency", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimReportParameter", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimSalutation", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimScheme", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimSecurity", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimSecurity_EWS_Today", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimSplCategory", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimStages", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimStagesMatrix", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimState", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimState_ucosite", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimSubSector", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimType", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimTypeServiceSummon", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimUserDeletionReason", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimUserDeptGroup", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimUserInfo", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimUserLocation", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimUserParameters", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimUserRole", "EffectiveToTimeKey")
        dt.Rows.Add("dbo", "DimZone", "EffectiveToTimeKey")
        dt.Rows.Add("INFO", "DimCompany", "EffectiveToTimeKey")
        dt.Rows.Add("INFO", "DimCompany_A", "EffectiveToTimeKey")
        dt.Rows.Add("INFO", "DimCompanyDir", "")
        dt.Rows.Add("legal", "DimActionablePnt", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimAdjournmentSought", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimAdjournReasonMobAAP", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimAdjudicatingAuthority", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "dimadvocateadinterimorder", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "dimadvocatesuitstage", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "dimadvocatesuittype", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimAOD_ExtenProof", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimArbiOrderJudgmnt", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimArbitationLanguage", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimArbitrationReason", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimArbitrationStages", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimAwardGross", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimAwardMinoR", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimAwardReason", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimAwardStaff", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimAwardStaffCategory", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimAwardType", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimBankruptcyInitiatedby", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimBOComplainantRelation", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimBOComplaintFiledBy", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimBOComplaintOutsidePurviewofOmbudsman", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimBOFurtureRecourse", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimBOGroundsOfComplaint", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimBOGroundsOfRejection", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimBONatureofComplaint", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimBOOrderPassed", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimBOReasonforapproachingOmbudsman", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimBOTypeofClaim", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimComplaintFiledAgainst", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimComplaintFiledBy", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimComplaintThrough", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimConditionsGrounds", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimDecreeType", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimDiscipAction", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimDisciplinaryAction", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimDRT_DRAT", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimDRTLegalAdjournment", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimDRTLegalAdjournReason", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimDRTSuitStages", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimDRTType", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimEmailSMSTemplate", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimExpenseType", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimFreshInfo", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimFutureActionSRFDtls", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimFutureRecourse", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimGroundsOfApplication", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimGroundsOfObjection", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimHighCourt", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimInsolvancyFutureRecourse", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimInsolvancyLiquidation", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimInsolvancyRevivalPlan", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimInterestFreq", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimInterimMsr", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimInterimOrdAgainstDebtor", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimInvestigationStatus", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimIRPInitialisedBy", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimLegalActionSought", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "dimlegaladjournment", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "dimlegaladjournreason", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimLegalComplaintCourtName", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimLegalComplaintLevel", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimLegalComplaintNature", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimLegalComplaintStatus", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimLegalCourtName", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimLegalCourtsForNIAct", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimLegalFavorAg", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimLegalJudgement", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimLegalJugFavorAg", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimLegalMExecDecre", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimLegalNatureOfActivity", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimLegalNextDtSaleResn", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimLegalNextPostPurpose", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimLegalNonLegalAction", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimLegalPlaintiffRelation", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimLegalPossessionResn", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimLegalPrayerStatus", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimLegalRCType", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimLegalReasonForReturning", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimLegalRecommendedAction", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimLegalSaleNonSale", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimLegalSuitUnder", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimLegalTypeSubSerSum", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimLegalWritPetitionAppealBy", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimMiscSuit", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimNatureofLapse", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimNatureOfProcessMaster", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimNextPostingPurpose", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimNonLegalAction", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimObjectionDisposalMode", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimOfficialMinorPenelty", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimOfficialNotHeld", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimOfficialStaff", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimOmbudsman", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimPossesionPendingReason", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimPostJudgmentStatus", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimPrayervalue", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimPreInvestigation", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimProfessionalCommDetail", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimProfessionalCommDetail_Mod", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimProfessionalDetail", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimProfessionalDetail_Mod", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimReasonDismissal", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimReasonforDeclarationofbankruptcyMaster", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimReasonForTermination", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimReasonService", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimReceivedFrom", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimRemarkKeyWord", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimRestrictiononMoratoriumPeriod", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimRTIApplicantType", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimRTIFurnishInfoN", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimRtiInfoSougth", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "Dimrtisourceinfo", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimSMS_EmailTemplate", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimSrfReason", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimSuitBy", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimSuitBYType", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimSuitStages", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimSuitType", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimSuitUnderDecision", "EffectiveToTimeKey")
        dt.Rows.Add("legal", "DimWithdrawalReason", "EffectiveToTimeKey")
        Return dt
    End Function



    ''data tables
    Public Function getdataTables() As DataTable
        Dim dt As New DataTable
        dt.Columns.Add("Schema")
        dt.Columns.Add("TableName")
        dt.Columns.Add("Filter")

        dt.Rows.Add("CURDAT", "CUSTOMERBASICDETAIL", "EffectiveToTimeKey")
        dt.Rows.Add("CURDAT", "ADVCUSTFINANCIALDETAIL", "EffectiveToTimeKey BranchCode")
        dt.Rows.Add("CURDAT", "ADVCUSTNONFINANCIALDETAIL", "EffectiveToTimeKey BranchCode")
        dt.Rows.Add("CURDAT", "ADVCUSTNPADETAIL", "EffectiveToTimeKey")
        dt.Rows.Add("CURDAT", "ADVCUSTOTHERDETAIL", "EffectiveToTimeKey")
        dt.Rows.Add("CURDAT", "ADVACBASICDETAIL", "EffectiveToTimeKey BranchCode")
        dt.Rows.Add("CURDAT", "ADVFACBILLDETAIL", "EffectiveToTimeKey")
        dt.Rows.Add("CURDAT", "ADVFACPCDETAIL", "EffectiveToTimeKey")
        dt.Rows.Add("CURDAT", "ADVFACCCDETAIL", "EffectiveToTimeKey")
        dt.Rows.Add("CURDAT", "ADVFACDLDETAIL", "EffectiveToTimeKey")
        dt.Rows.Add("CURDAT", "ADVACFINANCIALDETAIL", "EffectiveToTimeKey")
        dt.Rows.Add("CURDAT", "ADVACOTHERDETAIL", "EffectiveToTimeKey")
        dt.Rows.Add("CURDAT", "ADVACRESTRUCTUREDETAIL", "EffectiveToTimeKey")
        dt.Rows.Add("CURDAT", "ADVACBALANCEDETAIL", "EffectiveToTimeKey")
        dt.Rows.Add("CURDAT", "ACDAILYTXNDETAIL", "")
        dt.Rows.Add("CURDAT", "ADVCUSTCAL", "EffectiveToTimeKey")
        dt.Rows.Add("CURDAT", "ADVACCAL", "EffectiveToTimeKey")
        dt.Rows.Add("CURDAT", "ADVACRELATIONS", "EffectiveToTimeKey")
        dt.Rows.Add("CURDAT", "ADVCUSTRELATIONSHIP", "EffectiveToTimeKey")
        dt.Rows.Add("CURDAT", "ADVCUSTCOMMUNICATIONDETAIL", "")
        dt.Rows.Add("CURDAT", "ADVNFACBASICDETAIL", "EffectiveToTimeKey")
        dt.Rows.Add("CURDAT", "ADVFACNFDETAIL", "EffectiveToTimeKey")
        dt.Rows.Add("CURDAT", "ADVNFACFINANCIALDETAIL", "EffectiveToTimeKey")
        dt.Rows.Add("CURDAT", "ADVSECURITYVALUEDETAIL", "EffectiveToTimeKey")
        dt.Rows.Add("DBO", "ADVSECURITYCRMDETAIL", "EffectiveToTimeKey")
        dt.Rows.Add("CURDAT", "ADVSECURITYINSURANCEDETAIL", "EffectiveToTimeKey")
        Return dt
    End Function

    
End Class
